version: "3.8"

services:
  angular-app:
    image: your_docker_username/test-deploy-angular-app:stage # Tag for stage environment
    container_name: test-deploy-angular-stage
    ports:
      - "8082:80" # Stage app on port 8082
    volumes:
      - ./nginx-stage.conf:/etc/nginx/conf.d/default.conf
    restart: always
