version: "3.8"

services:
  angular-app:
    image: hasbynatawijaya/test-deploy-angular:dev # Tag for dev environment
    container_name: test-deploy-angular-dev
    ports:
      - "8081:80" # Dev app on port 8081
    volumes:
      - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf
    restart: always
